default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cue_development

test:
  <<: *default
  database: cue_test

production:
  <<: *default
  database: cue_production
  username: cue
  password: <%= ENV['IDX_DATABASE_PASSWORD'] %>
